remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: CKP
description: Pure Python implementations of competitive programming algorithms.

sidebar:
  - example
  - data_structure
  - graph_theory
  - number_theory
  - numeric