remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: katex

title: CKP
description: Pure Python implementations of competitive programming algorithms.