name: Test CKP
on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.10', '3.13', 'pypy3.10']
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setting Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Run Tests
      run: python -m test -v